---

version: "3.5"

networks:
    authenticator:
        driver: bridge

volumes:
    pgdata:

    pgadmindata:

services:
    postgres:
        image: postgres:9.4
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - authenticator
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"

    authenticator-ldap:
        image: tacc/slapd
        networks:
            - authenticator
        environment:
          LDAP_DOMAIN: "tapis"
          LDAP_ORGANISATION: "Tapis"
          LDAP_ROOTPASS: "a1r2c3HKvv0"

    migrations:
        image: tapis/authenticator-migrations
        volumes:
            - ./config-local.json:/home/tapis/config.json
        networks:
            - authenticator

    authenticator:
        image: tapis/authenticator
        ports:
            - "5000:5000"
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - ./service.log:/home/tapis/service.log
        networks:
            - authenticator
        depends_on:
            - postgres

    authenticator-tests:
        image: tapis/authenticator-tests
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - ./service.log:/home/tapis/service.log
        networks:
            - authenticator


    pgadmin:
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: "admin@test.com"
          PGADMIN_DEFAULT_PASSWORD: "password"
        ports:
            - "8000:80"
        networks:
            - authenticator
        depends_on:
          - postgres
        volumes:
            - pgadmindata:/var/lib/pgadmin

