# image: tapis/authenticator-migrations
FROM tapis/authenticator

RUN pip install --upgrade alembic==1.10.4
RUN pip install --upgrade Flask-Migrate==4.0.7

COPY migrations /home/tapis/migrations

ENV MIGRATIONS_RUNNING=True

USER root
RUN chown -R tapis:tapis /home/tapis
USER tapis

ENTRYPOINT ["flask", "db"]