# image: tapis/authenticator-migrations
from tapis/authenticator

RUN pip install --upgrade alembic==1.10.4
COPY migrations /home/tapis/migrations

ENV MIGRATIONS_RUNNING=True

User root
RUN chown -R tapis:tapis /home/tapis
USER tapis

ENTRYPOINT ["flask", "db"]