# image: tapis/authenticator-migrations
from tapis/authenticator

COPY migrations /home/tapis/migrations

ENV MIGRATIONS_RUNNING=True

User root
RUN chown -R tapis:tapis /home/tapis
USER tapis

ENTRYPOINT ["flask", "db"]