---

version: "3.5"

networks:
    authenticator:
        driver: bridge

volumes:
    pgdata:

services:
    postgres:
        image: postgres:9.4
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - authenticator
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"

    authenticator-ldap:
        image: tacc/slapd
        networks:
            - authenticator
        environment:
          LDAP_DOMAIN: "tapis"
          LDAP_ORGANISATION: "Tapis"
          LDAP_ROOTPASS: "a1r2c3HKvv0"

    migrations:
        image: tapis/authenticator-migrations
        volumes:
            - ./config-local.json:/home/tapis/config.json
        networks:
            - authenticator

    authenticator:
        image: tapis/authenticator
        ports:
            - "5000:5000"
        volumes:
            - ./config-local.json:/home/tapis/config.json
            - ./service.log:/home/tapis/service.log
        networks:
            - authenticator
        depends_on:
            - postgres

