# Recipes for building images, and applying data migrations and running services locallu.
# NOTE - tab characters are required within recipes; Do NOT edit this file in an editor that supplies spaces; for example,
#        lots of Python IDEs like PyCharm won't work because they are (rightly) configured to insert spaces, even if you
#        type a TAB character. If you see an error like " *** missing separator.  Stop." you're missing some tabs!
#
#        CONSIDER USING VIM (sigh!) WHICH ACTUALLY HAS GOOD MAKEFILE EDITING SUPPORT.


# it is required that the operator export API_NAME=<name_of_the_api> before using this makefile/
# default to authenticator
API_NAME ?=authenticator
api=${API_NAME}

cwd=$(shell pwd)


# ----- build images

build.api:
	# cd $(cwd); touch service.log; chmod a+w service.log; docker build -t tapis/$(api) .;
	cd $(cwd); touch service.log; chmod a+w service.log; docker-compose -f docker-compose-kprice.yml build authenticator-api; echo 'Finished building tapis/authenticator-api:latest'; echo;

build.ldap:
	cd $(cwd); docker compose -f docker-compose-kprice.yml build authenticator-ldap; echo 'Finished building tapis/authenticator-ldap:latest'; echo;

build.migrations:
	# cd $(cwd); docker build -f Dockerfile-migrations -t tapis/$(api)-migrations .
	cd $(cwd); docker compose -f docker-compose-kprice.yml build authenticator-migrations; echo 'Finished building tapis/authenticator-migrations:latest'; echo;

build.test:
	# cd $(cwd); docker build -t tapis/$(api)-tests -f Dockerfile-tests .;
	cd $(cwd); docker compose -f docker-compose-kprice.yml build authenticator-tests; echo 'Finished building tapis/authenticator-tests:latest'; echo;

build: build.api build.migrations build.test

# ----- run tests
# TODO: this can't be run on its own, since there are some tests that require the DBs to be empty.
# either make setup/teardown modules for these tests or edit the tests so that it's not required anymore
test: build.test
	cd $(cwd); touch service.log; chmod a+w service.log; docker compose -f docker-compose-kprice.yml build $(api)-tests; docker compose -f docker-compose-kprice.yml run $(api)-tests;

# ----- shutdown the currently running services
down:
	docker-compose -f docker-compose-kprice.yml down

# ----- wipe the local environment by removing all data and containers
clean: down
	- docker volume rm $(api)_pgdata
	- docker volume rm $(api)_pgadmindata
	- docker volume rm $(api)_ldapdata

# ----- start databases
run.dbs: build.api 
	# cd $(cwd); docker-compose --compatibility up -d postgres; docker-compose up -d authenticator-ldap
	cd $(cwd); docker compose --compatibility -f docker-compose-kprice.yml up -d authenticator-postgres; docker compose -f docker-compose-kprice.yml up -d authenticator-ldap;

run.api: build.api
	cd $(cwd); docker compose -f docker-compose-kprice.yml --compatibility up -d authenticator-api

run: down
	run.dbs run.api

# ----- connect to db as root
connect_db:
	docker-compose exec authenticator-postgres psql -U authenticator

# ----- initialize databases; run this target once per database installation
init_dbs: run.dbs
	echo "wait for db to start up..."
	sleep 8
	docker cp new_db.sql $(api)-postgres:/db.sql
	docker compose -f docker-compose-kprice.yml exec -T $(api)-postgres psql -U authenticator -f /db.sql

# ----- wipe database and associated data
#wipe: clean
#	rm -rf migrations

# ----- run migrations
migrate.upgrade: build.migrations
	docker compose -f docker-compose-kprice.yml run --rm authenticator-migrations upgrade
