# Recipes for building images, and applying data migrations and running services locallu.
# NOTE - tab characters are required within recipes; Do NOT edit this file in an editor that supplies spaces; for example,
#        lots of Python IDEs like PyCharm won't work because they are (rightly) configured to insert spaces, even if you
#        type a TAB character. If you see an error like " *** missing separator.  Stop." you're missing some tabs!
#
#        CONSIDER USING VIM (sigh!) WHICH ACTUALLY HAS GOOD MAKEFILE EDITING SUPPORT.



# To run tests ensure service_password and token_url in .env
# make clean
# make build
# make init_dbs
# make migrate.upgrade
# make test

# it is required that the operator export API_NAME=<name_of_the_api> before using this makefile/
# default to authenticator
API_NAME ?=authenticator
api=${API_NAME}

cwd=$(shell pwd)

# the name of the docker compose command; for older systems that, set cmp=docker-compose
cmp ?= docker compose


# ----- build images

build.api:
	cd $(cwd); touch service.log; chmod a+w service.log; docker build -t tapis/$(api) .;

build.migrations:
	cd $(cwd); docker build -f Dockerfile-migrations -t tapis/$(api)-migrations .

build.test:
	cd $(cwd); docker build -t tapis/$(api)-tests -f Dockerfile-tests .;

build: build.api build.migrations build.test

# ----- run tests
test: build.test
	cd $(cwd); touch service.log; chmod a+w service.log; $(cmp) run -e MFA_GEN_CODE=$(MFA_GEN_CODE) $(api)-tests;

# ----- shutdown the currently running services
down:
	$(cmp) down

# ----- wipe the local environment by removing all data and containers
clean: down
	- docker volume rm $(api)_pgdata

# ----- start databases
run_dbs: build.api down
	cd $(cwd); $(cmp) --compatibility up -d postgres; $(cmp) up -d authenticator-ldap

# ----- connect to db as root
connect_db:
	$(cmp) exec postgres psql -Upostgres

# ----- initialize databases; run this target once per database installation
init_dbs: run_dbs
	echo "wait for db to start up..."
	sleep 8
	docker cp new_db.sql $(api)_postgres_1:/db.sql
	$(cmp) exec -T postgres psql -Upostgres -f /db.sql

# ----- wipe database and associated data
#wipe: clean
#	rm -rf migrations

# ----- run migrations
migrate.upgrade: build.migrations
	$(cmp) run --rm migrations upgrade
