"""empty message

Revision ID: 0440c75fcfb1
Revises: ca442ccae0dd
Create Date: 2023-04-22 13:50:15.758985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0440c75fcfb1'
down_revision = 'ca442ccae0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorization_codes', sa.Column('tapis_idp_id', sa.String(length=50), nullable=True))
    op.add_column('authorization_codes', sa.Column('tapis_mfa', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authorization_codes', 'tapis_mfa')
    op.drop_column('authorization_codes', 'tapis_idp_id')
    # ### end Alembic commands ###
