"""empty message

Revision ID: 2418c11958b0
Revises: 4a77eb27b904
Create Date: 2021-12-06 23:33:57.229089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2418c11958b0'
down_revision = '4a77eb27b904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('active', sa.Boolean(), nullable=True))
    op.execute(f"UPDATE clients set active = True;")
    op.alter_column('clients', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'active')
    # ### end Alembic commands ###
