"""empty message

Revision ID: 6df17a83c1fc
Revises: 0440c75fcfb1
Create Date: 2023-04-22 16:46:13.871244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df17a83c1fc'
down_revision = '0440c75fcfb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_codes', sa.Column('tapis_idp_id', sa.String(length=50), nullable=True))
    op.add_column('device_codes', sa.Column('tapis_mfa', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_codes', 'tapis_mfa')
    op.drop_column('device_codes', 'tapis_idp_id')
    # ### end Alembic commands ###
