"""empty message

Revision ID: 88c463c61227
Revises: c86f280e33bc
Create Date: 2019-12-03 15:37:34.636202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c463c61227'
down_revision = 'c86f280e33bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_display_name_key', 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('clients_display_name_key', 'clients', ['display_name'])
    # ### end Alembic commands ###
