"""empty message

Revision ID: acf5fe06e3c5
Revises: 9983be60f4e8
Create Date: 2022-08-29 21:13:13.051665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf5fe06e3c5'
down_revision = '9983be60f4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_access_tokens_client_id'), 'access_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_access_tokens_jti'), 'access_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_access_tokens_subject'), 'access_tokens', ['subject'], unique=False)
    op.create_index(op.f('ix_access_tokens_tenant_id'), 'access_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_access_tokens_token_create_time'), 'access_tokens', ['token_create_time'], unique=False)
    op.create_index(op.f('ix_access_tokens_username'), 'access_tokens', ['username'], unique=False)
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_clients_tenant_id'), 'clients', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_clients_username'), 'clients', ['username'], unique=False)
    # op.drop_constraint('clients_client_id_key', 'clients', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_subject'), 'refresh_tokens', ['subject'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_tenant_id'), 'refresh_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_create_time'), 'refresh_tokens', ['token_create_time'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_username'), 'refresh_tokens', ['username'], unique=False)
    op.create_index(op.f('ix_tenantconfig_tenant_id'), 'tenantconfig', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenantconfig_tenant_id'), table_name='tenantconfig')
    op.drop_index(op.f('ix_refresh_tokens_username'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_create_time'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_tenant_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_subject'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    # op.create_unique_constraint('clients_client_id_key', 'clients', ['client_id'])
    op.drop_index(op.f('ix_clients_username'), table_name='clients')
    op.drop_index(op.f('ix_clients_tenant_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_index(op.f('ix_access_tokens_username'), table_name='access_tokens')
    op.drop_index(op.f('ix_access_tokens_token_create_time'), table_name='access_tokens')
    op.drop_index(op.f('ix_access_tokens_tenant_id'), table_name='access_tokens')
    op.drop_index(op.f('ix_access_tokens_subject'), table_name='access_tokens')
    op.drop_index(op.f('ix_access_tokens_jti'), table_name='access_tokens')
    op.drop_index(op.f('ix_access_tokens_client_id'), table_name='access_tokens')
    # ### end Alembic commands ###
