"""empty message

Revision ID: c86f280e33bc
Revises: 
Create Date: 2019-12-03 15:13:13.636555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86f280e33bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('client_key', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('callback_url', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('last_update_time', sa.DateTime(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_table('authorization_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(length=80), nullable=False),
    sa.Column('client_key', sa.String(length=80), nullable=False),
    sa.Column('redirect_url', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorization_codes')
    op.drop_table('clients')
    # ### end Alembic commands ###
