"""1.8.5 authenticator - added nonce

Revision ID: c92a84086513
Revises: 1.3.4
Create Date: 2025-07-03 15:50:37.726308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92a84086513'
down_revision = '1.3.4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorization_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passthrough_nonce', sa.String(length=200), nullable=True))

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('clients_client_id_key', type_='unique')

    with op.batch_alter_table('device_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passthrough_nonce', sa.String(length=200), nullable=True))

    with op.batch_alter_table('tenantconfig', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tenantconfig_tenant_id', type_='unique')
        batch_op.drop_index('ix_tenantconfig_tenant_id')
        batch_op.create_index(batch_op.f('ix_tenantconfig_tenant_id'), ['tenant_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenantconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenantconfig_tenant_id'))
        batch_op.create_index('ix_tenantconfig_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_unique_constraint('uq_tenantconfig_tenant_id', ['tenant_id'])

    with op.batch_alter_table('device_codes', schema=None) as batch_op:
        batch_op.drop_column('passthrough_nonce')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint('clients_client_id_key', ['client_id'])

    with op.batch_alter_table('authorization_codes', schema=None) as batch_op:
        batch_op.drop_column('passthrough_nonce')

    # ### end Alembic commands ###
