"""empty message

Revision ID: ca442ccae0dd
Revises: acf5fe06e3c5
Create Date: 2023-04-20 15:29:31.465644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca442ccae0dd'
down_revision = 'acf5fe06e3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenantconfig_tenant_id', table_name='tenantconfig')
    op.create_index(op.f('ix_tenantconfig_tenant_id'), 'tenantconfig', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenantconfig_tenant_id'), table_name='tenantconfig')
    op.create_index('ix_tenantconfig_tenant_id', 'tenantconfig', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
