"""empty message

Revision ID: ca442ccae0dd
Revises: acf5fe06e3c5
Create Date: 2023-04-20 15:29:31.465644

"""
from alembic import op
import sqlalchemy as sa
from tapisservice.logs import get_logger
logger = get_logger(__name__)


# revision identifiers, used by Alembic.
revision = 'ca442ccae0dd'
down_revision = 'acf5fe06e3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    logger.info("Starting ca442ccae0dd upgrade")
    op.create_unique_constraint("uq_tenantconfig_tenant_id", "tenantconfig", ["tenant_id"])
    logger.info("Uniqueness constraint for tenant_id on TenantConfig created.")
    logger.info("Migration ca442ccae0dd_ complete.")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_tenantconfig_tenant_id", "tenantconfig")
    # ### end Alembic commands ###
