"""empty message

Revision ID: fb0d3648b5c6
Revises: 1.3.4
Create Date: 2025-07-28 21:04:06.917078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0d3648b5c6'
down_revision = '1.3.4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorization_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passthrough_nonce', sa.String(length=200), nullable=True))

    with op.batch_alter_table('device_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passthrough_nonce', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_codes', schema=None) as batch_op:
        batch_op.drop_column('passthrough_nonce')

    with op.batch_alter_table('authorization_codes', schema=None) as batch_op:
        batch_op.drop_column('passthrough_nonce')

    # ### end Alembic commands ###
